#!/usr/bin/env bash

# disable var is unused
# shellcheck disable=SC2034

TICK_RATE=24 # number of frame per second

SIG_FORWARD=1
SIG_BACKWARD=2
SIG_RIGHT=3
SIG_LEFT=4
SIG_QUIT=5

stty -echo # disable user input

# shellcheck source=./display
source "./display"
# shellcheck source=./utils
source "./utils"

game_loop() {
	trap "delta_dir=1;" "$SIG_FORWARD"
	trap "delta_dir=-1;" "$SIG_BACKWARD"
	trap "delta_rotate=1;" "$SIG_RIGHT"
	trap "delta_rotate=-1;" "$SIG_LEFT"

	for i in $(seq 0 10); do
		local delta_dir=0
		local delta_rotate=0

		size=($(get_term_size))
		bars=($(gen_bars_temp size))

		render_frame bars size

		printf "delta_dir %d\ndelta_rotate %d" "$delta_dir" "$delta_rotate"

		sleep 1
	done
}

# Each tile is 100x100.
player_position=(150 150) # x and y position of the player
player_angle=0 # deg of rotation of the player value between (0-359)
game=(1 1 1 2
	1 0 0 2
	1 0 0 2
	2 1 0 1)
game_size=4

# print_game game "$game_size"

setup &
game_loop

clear_game
