#!/usr/bin/env bash

# disable var is unused
# shellcheck disable=SC2034

TICK_RATE=24 # number of frame per second
SIG_FORWARD=1
SIG_BACKWARD=2
SIG_RIGHT=3
SIG_LEFT=4

# shellcheck source=./display
# shellcheck source=./utils
source "./display"
source "./utils"

game_loop() {
	delta_dir=0
	rotate=0
	trap "delta_dir=1;" "$SIG_FORWARD"
	trap "delta_dir=-1;" "$SIG_BACKWARD"
	trap "rotate=1;" "$SIG_RIGHT"
	trap "rotate=-1;" "$SIG_LEFT"

	local inputs

	size=($(get_term_size))
	bars=($(gen_bars_temp size))
	render_frame bars size

	printf "%s " "${inputs[@]}"

	sleep 1
}

# Each tile is 100x100.
player_position=(150 150) # x and y position of the player
player_angle=0 # deg of rotation of the player value between (0-359)
game=(1 1 1 2
	1 0 0 2
	1 0 0 2
	2 1 0 1)
game_size=4

# print_game game "$game_size"

setup &
for i in $(seq 0 10); do
	game_loop
done

# game_loop
